services:
  backend:
    build:
      context: ./backend
    container_name: devbank-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: devbank-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend